name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        run: echo "##[set-output name=versoin;]$(cat .nvmrc)"
        id: node
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.node.outputs.version }}"
      - name: Build
        run: |
          npm ci
          npm run build
          cp dist/index.html dist/404.html
        # https://www.smashingmagazine.com/2016/08/sghpa-single-page-app-hack-github-pages/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist